version: "3.8"

version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3307:3307
    environment:
     
     - MYSQL_DATABASE=tpachato
     - MYSQL_USER=root
     - MYSQL_PASSWORD=


  spring_app:
    image: apachee1/achat
    container_name: achatspring
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://localhost:3306/tpachato?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     - 8089:8089
    depends_on:
     - mysqldb

  angular_app:
    image: anas1412/achatfront
    container_name: achatangular
    restart: on-failure
    ports:
     - 4200:80
    depends_on:
     - spring_app
